Update updater

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -107,7 +107,7 @@ function performupdate() {
 
     if [ "$update_channel" == "master" ]; then
         git fetch --force --depth 1 origin && git reset --hard origin/master
- git fetch --force --depth 1 origin || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/explowz/cathook\n\033[0m"; exit 1; } }
+        git fetch --force --depth 1 origin || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/explowz/cathook\n\033[0m"; exit 1; } }
     elif [ "$update_channel" == "developer" ]; then
         echo -e "\033[1;33mRunning in developer mode!\n\033[0m" && git pull origin --rebase=false || { echo -e "\033[1;31m\n\nFailed to pull from github!\n\033[0m"; exit 1; }
     else
@@ -139,18 +139,11 @@ function performupdate() {
         git submodule sync > /dev/null
         git submodule update --depth 1 --init --recursive
     fi
-
-
-    # Make sure that the auto updater only uses 1 core for compiling
-    proccount=$(grep -c '^processor' /proc/cpuinfo)
-    if [ "$AUTOUPDATER" == true ]; then
-        proccount=1
-    fi
-
+    
     #Create build folder in case it doesn't exist
     mkdir -p ./build
     # Update cathook
-    pushd build && cmake .. && cmake --build . --target cathook -- -j$proccount || { echo -e "\033[1;31m \n \nFailed to compile cathook\n\033[0m"; exit 1; }
+    pushd build && cmake .. && cmake --build . --target cathook -- -j$(nproc --all) || { echo -e "\033[1;31m \n \nFailed to compile cathook\n\033[0m"; exit 1; }
     # Update data
     cwd="$(pwd)"
     cmake --build . --target data || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory! Trying with root rights!\n\033[0m"; $SUDO bash -c "cd \"$cwd\"; cmake --build . --target data" || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory\n\033[0m"; exit 1; } }
